name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the honeycomb-server image
      run: cd honeycomb-server && docker build . --file Dockerfile --tag node2honeycomb/honeycomb-server:$(date +%s)
    
    - uses: actions/checkout@v2
    - name: Build the honeycomb-server-console image
      run: cd honeycomb-console && docker build . --file Dockerfile --tag node2honeycomb/honeycomb-console-server:$(date +%s)

